### ISSUE TITLE
UI text issues

### ISSUE THREAD

**Issue by feeshy** [tesselode/cocoa-delay#2]
Just found some text issues about the filter section:
<img width="130" alt="image" src="https://github.com/tesselode/cocoa-delay/assets/10860212/32cffff2-e2e3-4b8a-b9a8-6d234b6d90da">
The _Low cut_ knob is not a low CUT filter, but actually a low PASS one, and the _High cut_ knob is actually a high PASS filter.

**Comment by tesselode** [comment]
You are absolutely right that those labels are incorrect. I don't have Illustrator anymore. I can edit the vector assets with Affinity Designer, but the text comes out blurry in the export. The best solution to this would be to port the plugin to iPlug 2 to get a resizable vector interface, but that's a lot of work that I don't want to do right now. So for now, I will not be fixing this.
